resources:
    - name: testing_res
      type: PropertyBag
      configuration:
        key1: value1
        key2: value2

pipelines:
  - name: Pipeline_A
    steps:
      - name: step_a1
        type: Bash
        configuration:
          outputResources:
            - name: testing_res
          priority: 5
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
            - date=$(date)
            - write_output property_bag "date=$date"

  - name: Pipeline_B
    steps:
      - name: step_a2
        type: Bash
        configuration:
          inputResources:
            - name: testing_res
          priority: 6
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"