pipelines:
  - name: Chronological_Pipeline
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "Step 1"
            - sleep 30s
      - name: step2
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "Step 2"
            - sleep 30s
