resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{gitBranch}}$
      gitProvider: nawaz_gh

pipelines:
  - name: Check_Save_Tests
    steps:
      - name: checkSaveTests
        type: Bash
        execution: 
          onExecute:
            - pushd $res_self_repo_resourcePath
            - npm install
            - node generateTests.js
            - mkdir -p testReports
            - mv test-report.xml testReports/test-report.xml
            - save_tests testReports

          
