pipelines:
  - name: Chronological_Pipeline
    configuration:
      chronological: true
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "Step 1"
            - sleep 30s
