pipelines:
  - name: Only_Matrix
    steps:
      - name: matrix_demo_timeout
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - key1: value1
              key2: value2
            - key1: v1
              key2: v4
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - bar
          onComplete:
            - foo
              
              
