pipelines:
  - name: AffinityGroupSeriesTest4
    steps:
      - name: start
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_a
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_a1
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: step_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_a2
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: step_a1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_a3
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: step_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_b
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_b1
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: step_b
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_b2
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: step_b1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_b3
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: step_b1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: end
        type: Bash
        configuration:
          affinityGroup: group
          inputSteps:
            - name: step_b3
            - name: step_a3
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
