resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^tests-failing$
      gitProvider: nawaz_gh

  - name: matrix_property_bag_in
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: property_bag
    type: PropertyBag
    configuration:
      key1: value1

  # - name: incoming
  #   type: IncomingWebhook
  #   configuration:
  #     webhookName: incoming

pipelines:
  - name: Pipeline
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - echo "Step 1"
            - echo "Step1" >> file1
            - add_run_files ./file1 file

      - name: step2
        type: Bash
        configuration:
          outputResources:
            - name: property_bag
          inputSteps:
            - name: step1
        execution: 
          onStart:
            - restore_run_files file ./file
          onExecute:
            - echo "Step 2"
            - cat file
            - echo "Step 3" >> file
            - add_run_files ./file file
            - date=$(date)
            - write_output property_bag "date=$date"

      - name: step3
        type: Bash
        configuration:
          inputResources:
            - name: property_bag
        execution: 
          onStart:
            - restore_run_files file ./file
          onExecute:
            - cat file
            - echo "Step 3" >> file
            - add_run_files ./file file


          