resources:
  - name: resource_r
    type: PropertyBag
    configuration:
      key1: value1

pipelines:
- name: my_pipeline
  steps:
  - name: step_A
    configuration:
      outputResources:
        - resource_r
  - name: step_B
    configuration:
      inputSteps:
        - name: step_A 
  - name: step_C
    configuration:
      inputResources:
      - name: resource_r
        newVersionOnly: true
  - name: step_D
    configuration:
      inputSteps:
      - name: step_B
      - name: step_C
        status:
        - success
        - skipped
