pipelines:
  - name: SimpleTest
    steps:
      - name: start
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"  
      - name: step_a
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"     
      - name: step_b
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_d
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
      - name: step_c
        type: Bash
        configuration:
          inputSteps:
            - name: step_b
            - name: step_e
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_d
        type: Bash
        configuration:
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
            - sleep 30s

      - name: step_e
        type: Bash
        configuration:
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
            - sleep 30s