resources:
  - name: complex1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: complex2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: complex3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: complex4
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

pipelines:
  - name: Complex1
    steps:
      - name: start
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"  

      - name: step_a
        type: Bash
        configuration:
          inputSteps:
            - name: start
          outputResources:
            - name: complex1
          affinityGroup: group_a
          priority: 2
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"   

      - name: step_b
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
          priority: 3
          inputResources:
            - name: complex1
          outputResources:
            - name: complex2
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_c
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
          affinityGroup: group_a
          priority: 4
          inputResources:
            - name: complex1
            - name: complex2
          outputResources:
            - name: complex3
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_d
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
            - name: step_c
          affinityGroup: group_a
          priority: 5
          inputResources:
            - name: complex1
            - name: complex2
            - name: complex3
          outputResources:
            - name: complex4
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_e
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
            - name: step_c
            - name: step_d
          affinityGroup: group_a
          priority: 6
          inputResources:
            - name: complex1
            - name: complex2
            - name: complex3
            - name: complex4
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_f
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
            - name: step_c
            - name: step_d
            - name: step_e
          affinityGroup: group_a
          priority: 7
          inputResources:
            - name: complex1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"