resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh
  - name: bbs_repo
    type: GitRepo
    configuration:
      path: ~khazina/testing
      branches:
        include: ^master$
      gitProvider: nawaz_bbs

pipelines:
  - name: First_Pipeline_Long_Pipeline_Name_Long
    steps:
      - name: First_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
            - name: bbs_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - popd
            
      - name: Second_Step
        type: Bash
        configuration:
          inputSteps:
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
      - name: Third_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Second_Step
        execution: 
          onExecute:
            - echo "Step 2"
          
      - name: Fourth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Third_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
    
