resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh

pipelines:
  - name: First_Pipeline_Long_Pipeline_Name_Long
    steps:
      - name: First_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests
            - save_tests saveTests/empty
            - popd
    
