resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^tests-failing$
      gitProvider: nawaz_gh

  - name: m1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m2
    type: PropertyBag
    configuration:
      key1: value1

  - name: m3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m4
    type: PropertyBag
    configuration:
      key1: value1


pipelines:
  - name: BugPipeline
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: m4
          affinityGroup: group1
          outputResources:
            - name: m1
        execution: 
          onExecute:
            - echo "Step 1"

      - name: step2
        type: Bash
        configuration:
          affinityGroup: group1
          inputResources:
            - name: m1
            - name: m3
            - name: m4
        execution: 
          onExecute:
            - echo "Step 2"

      - name: step3
        type: Bash
        configuration:
          affinityGroup: group1
          outputResources:
            - name: m2
          inputResources:
            - name: m4
          inputSteps:
            - name: step2
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m2 "date1=$date"

      - name: step4
        type: Bash
        configuration:
          inputResources:
            - name: m2
            - name: m4
        execution: 
          onExecute:
            - echo "Step 4"

  - name: ResTrig
    steps:
      - name: trigger
        type: Bash
        configuration:
          affinityGroup: group1
          outputResources:
            - name: m4
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m4 "date1=$date"

  - name: ResTrig1
    steps:
      - name: trigger
        type: Bash
        configuration:
          affinityGroup: group1
          outputResources:
            - name: m3
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m3 "date1=$date"

  - name: ResTrig1
    steps:
      - name: trigger
        type: Bash
        configuration:
          affinityGroup: group1
          outputResources:
            - name: m3
            - name: m4
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m3 "date1=$date"
            - write_output m4 "date1=$date"
