resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh

  - name: matrix_property_bag_in
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: matrix_property_bag_out
    type: PropertyBag
    configuration:
      key1: value1

pipelines:
  - name: Pipeline
    steps:
      - name: matrix_2
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - delay: 1
              fail: 'true'
            - delay: 10
              fail: 'true'
            - delay: 15
              fail: 'false'
            - delay: 20
              fail: 'false' 
        execution:
          onStart:
            - sleep "$delay"
          onExecute:
            - echo "I am on matrix step"
            - |
              [ $fail == 'false' ] 
            - ls -l .

        fastFail: true

        # allowFailures:
        #   - environmentVariables:
        #       delay: 1
        #       fail: 'true'
              
        # exclude:
        #   - environmentVariables:
        #       delay: 10
        #       fail: 'true'
