resources:
    - name: res_test_1
      type: PropertyBag
      configuration:
        key1: value1
        key2: value2

pipelines:
  - name: ResourcePipeline
    steps:
      - name: start
        type: Bash
        configuration:
          outputResources:
             - name: res_test_1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
            
      - name: stepA
        type: Bash
        configuration:
          inputResources:
             - name: res_test_1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: stepB
        type: Bash
        configuration:
          inputResources:
            - name: res_test_1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
