pipelines:
  - name: Complex1
    steps:
      - name: start
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"  

      - name: step_a
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"   

      - name: step_b
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_c
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_d
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
            - name: step_c
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
            - sleep 30s

      - name: step_e
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
            - name: step_c
            - name: step_d
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
            - sleep 30s

      - name: step_f
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
            - name: step_c
            - name: step_d
            - name: step_e
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
            - sleep 30s