pipelines:
  - name: Pipeline
    steps:
      - name: step1
        type: Bash
        execution: 
          onExecute:
            - echo "Step 1"
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution: 
          onExecute:
            - echo "Step 2"
      - name: step3
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution: 
          onExecute:
            - echo "Step 3"
      - name: step4
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution: 
          onExecute:
            - echo "Step 4"
      - name: step5
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution: 
          onExecute:
            - echo "Step 5"
    
