pipelines:
  - name: FreeTier
    steps:
      - name: free
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Executing matrix step on ${steplet_id}"
              
              