resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh

pipelines:
  - name: Pipeline
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/empty/temp
            - save_tests saveTests/correct
            - echo "Passed"
            - popd

      - name: Matrix_Fan_Out
        type: Bash
        configuration:
          inputResources:
            - name: self_repo            
        execution: 
          onExecute:
            - echo "I am on fan out step"
            - touch fan_out.txt
            - echo "Fan out working" > fan_out.txt
            - add_run_files ./fan_out.txt inputFile

      - name: matrix_1
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
          inputSteps: 
            - name: Matrix_Fan_Out
        execution:
          onStart:
            - restore_run_files inputFile .
            - ls 
          onExecute:
            - echo "I am on matrix step"
            - touch ${steplet_id}_file
            - echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file
            - mkdir outputFiles
            - cp ./${steplet_id}_file files
            - add_run_files ./files/ outputFiles
          
      - name: Matrix_Fan_In
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
          inputSteps: 
            - name: matrix_1
        execution:
          onStart:
            - restore_run_files outputFiles ./outputFiles/.
          onExecute:
            - echo "Hello World"
            - ls -l ./outputFiles
        
    
