pipelines:
  - name: First_Pipeline
    steps:
      - name: First_Step
        type: Bash
        execution: 
          onExecute:
            - echo "Step 1"
            
      - name: Second_Step
        type: Bash
        configuration:
          inputSteps:
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
      - name: number_sometimes_shows_up_below
        type: Bash
        configuration:
          inputSteps:
            - name: Second_Step
        execution: 
          onExecute:
            - echo "Step 2"
          
      - name: Fourth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: number_sometimes_shows_up_below
        execution: 
          onExecute:
            - echo "Step 2"
            
    
