pipelines:
  - name: Pipeline_3
    configuration:
      environmentVariables:
        readOnly:
          ENV1: value1
          ENV2: value2
    steps:
      - name: Simple_Bash_1
        type: Bash
        execution:
          onStart:
            - add_run_variables "key1=value1"
          onExecute:
            - echo "$key1"
            - echo "$run_rumber"

      - name: Simple_Bash_2
        type: Bash
        configuration:
          inputSteps:
            - name: Simple_Bash_1
        execution:
          onStart:
            - add_run_variables "key2=value2"
          onExecute:
            - echo "$key1"
            - echo "$key2"
            - echo "Run number - $run_rumber"

      - name: Simple_Bash_3
        type: Bash
        configuration:
          inputSteps:
            - name: Simple_Bash_2
        execution:
          onStart:
            - add_run_variables "key3=value3"
          onExecute:
            - echo "$key1"
            - echo "$key2"
            - echo "$key3"
            - echo "Run number - $run_rumber"
