pipelines:
  - name: SimpleTest
    steps:
      - name: step_a
        type: Bash
        execution:
          configuration:
            affinityGroup: group_a
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"     
      - name: step_b
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_d
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
      - name: step_c
        type: Bash
        configuration:
          inputSteps:
            - name: step_b
          affinityGroup: group_a
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
      - name: step_d
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"