resources:
  - name: microGit1
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      gitProvider: nawaz_gh
      files:
        include: \bmicro\/.+\b
        
  - name: templateGit1
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      gitProvider: nawaz_gh
      files:
        include: \btemplate\/.+\b

pipelines:
  - name: BugPipeline1
    steps:
      - name: template_build
        type: Bash
        configuration:
          inputResources:
            - name: templateGit1
          affinityGroup: group1
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m1 "date1=$date"

      - name: micro_build
        type: Bash
        configuration:
          affinityGroup: group1
          inputResources:
            - name: microGit1
        execution: 
          onExecute:
            - echo "Step 2"

      - name: step3
        type: Bash
        configuration:
          affinityGroup: group1
          inputSteps:
            - name: micro_build
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m2 "date1=$date"

      - name: step4
        type: Bash
        configuration:
          inputSteps:
            - name: template_build
        execution: 
          onExecute:
            - echo "Step 4"

  # - name: ResTrig
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m4
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m4 "date1=$date"

  # - name: ResTrig1
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m3
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m3 "date1=$date"

  # - name: ResTrig3
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m3
  #           - name: m4
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m3 "date1=$date"
  #           - write_output m4 "date1=$date"
