pipelines:
  - name: Chronological_Step
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "Step 1"
            - sleep 2s
      - name: step2
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo "Step 2"
            - sleep 2s
