template: true
valuesFilePath: ./values.yml

pipelines:
  - name: testcron
    steps:
      - name: basic
        type: Matrix
        stepMode: Bash
        configuration:
          runtime:
            type: host
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            {{ range $i, $e := until 100 }}
            - foo: "bar{{$i}}"
              x: {{$i}}
            {{ end }}
        execution:
          onExecute:
            - |
              if [ $(($x % 10)) -eq 0 ]; then
                curl https://norvig.com/big.txt
              fi
