pipelines:
  - name: First_Pipeline
    steps:
      - name: First_Step
        type: Bash
        execution: 
          onExecute:
            - echo "Step 1"
            
      - name: Second_Step
        type: Bash
        configuration:
          inputSteps:
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
      - name: Third_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Second_Step
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
          
      - name: Fourth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Third_Step
            - name: Second_Step
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
      - name: Fifth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Fourth_Step
            - name: Third_Step
            - name: Second_Step
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
      - name: Sixth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Fifth_Step
            - name: Fourth_Step
            - name: Third_Step
            - name: Second_Step
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
      - name: Seventh_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Sixth_Step
            - name: Fifth_Step
            - name: Fourth_Step
            - name: Third_Step
            - name: Second_Step
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
