pipelines:
  - name: First_Pipeline
    steps:
      - name: First_Step
        type: Bash
        execution: 
          onExecute:
            - echo "Step 1"
      - name: Second_Step
        type: Bash
        configuration:
          inputSteps:
            - name: First_Step
        execution:
          onExecute:
            - echo "Step 2"
