resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh

pipelines:
  - name: Pipeline
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/empty/temp
            - save_tests saveTests/correct
            - echo "Passed"
            - popd

      - name: Matrix_Fan_Out_1
        type: FanOut
        configuration:
          inputSteps: 
            - name: Normal_Step
          inputResources:
            - name: self_repo            
        execution: 
          onExecute:
            - echo "I am on fan out step"
            - touch fan_out.txt
            - set_step_var fan_out value1
            - echo "Fan out working" > fan_out_1.txt
            - ls -l .

      - name: Matrix_Fan_Out_2
        type: FanOut
        configuration:
          inputSteps: 
            - name: Normal_Step
          inputResources:
            - name: self_repo            
        execution: 
          onExecute:
            - echo "I am on fan out step"
            - touch fan_out.txt
            - set_step_var fan_out value2
            - echo "Fan out working" > fan_out_2.txt
            - ls -l .

      - name: Matrix_Fan_Out_3
        type: FanOut
        configuration:
          inputSteps: 
            - name: Normal_Step
          inputResources:
            - name: self_repo            
        execution: 
          onExecute:
            - echo "I am on fan out step"
            - touch fan_out.txt
            - set_step_var fan_out value3
            - echo "Fan out working" > fan_out_3.txt
            - ls -l .

      - name: matrix
        type: Matrix
        stepMode: Bash
        configuration:
          inputResources:
            - name: self_repo
          inputSteps: 
            - name: Matrix_Fan_Out_1
            - name: Matrix_Fan_Out_2
            - name: Matrix_Fan_Out_3
          matrix:
            environmentVariables:
              env1: 
                - one
                - two

        execution:
          onStart:
            - restore_run_files inputFile .
            - ls 
          onExecute:
            - echo "I am on matrix step"
            - ls -l ./Matrix_Fan_Out_{1,2,3}
            - touch ${steplet_id}_file
            - echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file
            - echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >> ${steplet_id}_file
            - echo "Runtime image name - $step_image_name, Runtime image tag - $step_image_tag" >> ${steplet_id}_file
            - get_step_var Matrix_Fan_Out_1 fan_out
            - get_step_var Matrix_Fan_Out_2 fan_out
            - get_step_var Matrix_Fan_Out_3 fan_out
            - ls -l .
            
      - name: Matrix_Fan_In
        type: FanIn
        configuration:
          inputResources:
            - name: self_repo
          inputSteps: 
            - name: matrix
        execution:
          onStart:
            - restore_run_files outputFiles ./outputFiles/.
          onExecute:
            - echo "Hello World"
            - ls -l .
            - ls -l ./matrix
        
    
