resources:
  - name: resource_r2
    type: PropertyBag
    configuration:
      key1: value1

pipelines:
- name: my_pipeline_2
  steps:
  - name: step_A
    type: Bash
    configuration:
      outputResources:
        - name: resource_r2
    execution:
      onExecute:
       - echo "A"
  - name: step_B
    type: Bash
    configuration:
      inputSteps:
        - name: step_A
    execution:
      onExecute:
       - echo "B"
  - name: step_C
    type: Bash
    configuration:
      inputResources:
      - name: resource_r2
        newVersionOnly: true
    execution:
      onExecute:
       - echo "C"
  - name: step_D
    type: Bash
    execution:
      onExecute:
       - echo "D"
    configuration:
      inputSteps:
      - name: step_B
      - name: step_C
        status:
        - success
        - skipped
        
  - name: step_E
    type: Bash
    execution:
      onExecute:
       - echo "D"
    configuration:
      inputSteps:
      - name: step_C
