resources:
  - name: microGit
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{abcdefghgitBranchijklmn}}$
      gitProvider: nawaz_gh
      files:
        include: \bmicro\/.+\b
        
  - name: templateGit
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{gitBranch}}$
      gitProvider: nawaz_gh
      files:
        include: \btemplate\/.+\b

  - name: folder1
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{gitBranch}}$
      gitProvider: nawaz_gh
      files:
        include: \bfolder1\/.+\b

  - name: folder2
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{gitBranch}}$
      gitProvider: nawaz_gh
      files:
        include: \bfolder2\/.+\b


  - name: folder3
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{gitBranch}}$
      gitProvider: nawaz_gh
      files:
        include: \bfolder3\/.+\b


  - name: m1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m2
    type: PropertyBag
    configuration:
      key1: value1

  - name: m3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m4
    type: PropertyBag
    configuration:
      key1: value1

pipelines:
  - name: BugPipeline2
    steps:
      - name: template_build
        type: Bash
        configuration:
          inputResources:
            - name: templateGit
          affinityGroup: group1
          outputResources:
            - name: m1
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m1 "date1=$date"

      - name: folder1_build
        type: Bash
        configuration:
          inputResources:
            - name: folder1
          affinityGroup: group1
          outputResources:
            - name: m1
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m1 "date1=$date"


      - name: folder2_build
        type: Bash
        configuration:
          inputResources:
            - name: folder2
          affinityGroup: group1
          outputResources:
            - name: m1
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m1 "date1=$date"


      - name: folder3_build
        type: Bash
        configuration:
          inputResources:
            - name: folder3
          affinityGroup: group1
          outputResources:
            - name: m1
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m1 "date1=$date"

      - name: micro_build
        type: Bash
        configuration:
          affinityGroup: group1
          inputResources:
            - name: m1
            - name: microGit
        execution: 
          onExecute:
            - echo "Step 2"

      - name: step3
        type: Bash
        configuration:
          affinityGroup: group1
          outputResources:
            - name: m2
          inputSteps:
            - name: micro_build
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m2 "date1=$date"

      - name: step4
        type: Bash
        configuration:
          inputResources:
            - name: m2
        execution: 
          onExecute:
            - echo "Step 4"

  # - name: ResTrig
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m4
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m4 "date1=$date"

  # - name: ResTrig1
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m3
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m3 "date1=$date"

  # - name: ResTrig3
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m3
  #           - name: m4
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m3 "date1=$date"
  #           - write_output m4 "date1=$date"
