pipelines:
  - name: Scenario_1
    steps:
      - name: step_A
        type: Bash
        execution:
          onExecute:
            - echo "Step 1"
      - name: step_B
        type: Bash
        configuration:
          inputSteps:
            - name: step_A
              status:
                - "cancelled"
        execution:
          onExecute:
            - echo "Step 2"
  - name: Scenario_2
    configuration:
      environmentVariables:
        readOnly:
          killA:
            allowCustom: true
            default: "false"
          killB:
            allowCustom: true
            default: "false"
    steps:
      - name: trigger
        type: Bash
        execution:
          onExecute:
            - echo 'Start'
      - name: step_A
        type: Bash
        configuration:
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - |
              if [ "${killA}" = "true" ]; then
                exit 1
              fi
      - name: step_B
        type: Bash
        configuration:
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - |
              if [ "${killB}" = "true" ]; then
                exit 1
              fi
      - name: step_C
        type: Bash
        configuration:
          inputSteps:
            - name: step_A
              status:
                - failure
                - error
                - timeout
            - name: step_B
        execution:
          onExecute:
            - echo "Executing step_C"
            - printenv
  - name: Scenario_3
    configuration:
      environmentVariables:
        readOnly:
          sleep:
            allowCustom: true
            default: "1"
    steps:
      - name: trigger
        type: Bash
        execution:
          onExecute:
            - echo 'Start'
      - name: step_A
        type: Bash
        configuration:
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - echo 'Success'
      - name: step_B
        type: Bash
        configuration:
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - exit 1
      - name: step_C
        type: Bash
        configuration:
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - sleep "${sleep}s"
      - name: step_D
        type: Bash
        configuration:
          inputSteps:
            - name: step_A
            - name: step_B
              status:
                - failure
            - name: step_C
              status:
                - timeout
        execution:
          onExecute:
            - echo "Executing step_C"
            - printenv

      - name: step_E
        type: Bash
        configuration:
          inputSteps:
            - name: step_D
              status:
                - success
                - skipped
        execution:
          onExecute:
            - echo "Executing step_C"
            - printenv