pipelines:
  - name: Multi_Node
    steps:
      - name: matrix_demo
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
          chronological: true
        stepletMultipliers:
          environmentVariables:
            - key1: value1
              key2: value2
            - key1: v1
              key2: v2
            - key1: v3
              key2: v4
            - key1: v5
              key2: v6
        execution:
          onExecute:
            - sleep 5s
            - echo "Executing matrix step on ${steplet_id}"
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: matrix_demo
        execution:
          onExecute:
            - sleep 10s
              
              
