pipelines:
  - name: Chronological_Pipeline
    steps:
      - name: step1
        type: Bash
        configuration:
          chronological: true
        execution:
          onExecute:
            - echo "Step 1"
            - sleep 30s
