resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh

pipelines:
  - name: Pipeline
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/empty/temp
            - save_tests saveTests/correct
            - echo "Passed"
            - popd

      - name: Matrix_Fan_Out
        type: Bash
        configuration:
          inputResources:
            - name: self_repo            
        execution: 
          onExecute:
            - echo "I am on fan out step"
            - touch fan_out.txt
            - echo "Fan out working" > fan_out.txt
            - add_run_files ./fan_out.txt inputFile

      - name: matrix_1
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
          inputSteps: 
            - name: Matrix_Fan_Out
          matrix:
            environmentVariables:
              env1: 
                - one
                - two

        execution:
          onStart:
            - restore_run_files inputFile .
            - ls 
          onExecute:
            - echo "I am on matrix step"
            - touch ${steplet_id}_file
            - echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file
            - echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >> ${steplet_id}_file
            - echo "Runtime image name - $step_image_name, Runtime image tag - $step_image_tag" >> ${steplet_id}_file
            - mkdir files
            - cp ./${steplet_id}_file files
            - add_run_files ./files/ outputFiles
          
      - name: Matrix_Fan_In
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
          inputSteps: 
            - name: matrix_2
        execution:
          onStart:
            - restore_run_files outputFiles ./outputFiles/.
          onExecute:
            - echo "Hello World"
            - ls -l ./outputFiles
            - find ./outputFiles -type f -printf "\n%p\n" -exec cat {} \;

      - name: matrix_2
        type: Matrix
        stepMode: Bash
        configuration:
          inputResources:
            - name: self_repo
          inputSteps: 
            - name: Matrix_Fan_Out
          matrix:
            environmentVariables:
              env1: 
                - one
                - two

        execution:
          onStart:
            - restore_run_files inputFile .
            - ls 
          onExecute:
            - echo "I am on matrix step"
            - touch ${steplet_id}_file
            - echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file
            - echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >> ${steplet_id}_file
            - echo "Runtime image name - $step_image_name, Runtime image tag - $step_image_tag" >> ${steplet_id}_file
            - mkdir files
            - cp ./${steplet_id}_file files
            - add_run_files ./files/ outputFiles
        
    
