pipelines:
  - name: Only_Matrix
    steps:
      - name: matrix_demo
        type: Matrix
        stepMode: Bash
        configuration:
          timeoutSeconds: 7200
        stepletMultipliers:
          environmentVariables:
            - key1: value1
              key2: value2
            - key1: v1
              key2: v4
        execution:
          onExecute:
            - sleep 45m
            - echo "Executing matrix step on ${steplet_id}"
              
              
