resources:
  - name: resource_r4
    type: PropertyBag
    configuration:
      key1: value1

pipelines:
- name: my_pipeline_4
  steps:
  - name: step_A
    type: Bash
    configuration:
      outputResources:
        - name: resource_r4
    execution:
      onExecute:
       - echo "A"
  - name: step_B
    type: Bash
    configuration:
      inputSteps:
        - name: step_A
    execution:
      onExecute:
       - echo "B"
  - name: step_C
    type: Bash
    configuration:
      inputResources:
      - name: resource_r4
        newVersionOnly: true
    execution:
      onExecute:
       - echo "C"
       
  - name: step_C1
    type: Bash
    configuration:
      inputSteps:
      - name: step_C
    execution:
      onExecute:
       - echo "C1"
       
  - name: step_D
    type: Bash
    execution:
      onExecute:
       - echo "D"
    configuration:
      inputSteps:
      - name: step_C1
      - name: step_C
        status:
        - success
        - skipped
        
  - name: step_D1
    type: Bash
    configuration:
      inputSteps:
      - name: step_D
    execution:
      onExecute:
       - echo "D1"
        
  - name: step_E
    type: Bash
    execution:
      onExecute:
       - echo "D"
    configuration:
      inputSteps:
      - name: step_D1
      - name: step_D
        status:
        - success
        - skipped
        
  - name: step_F
    type: Bash
    execution:
      onExecute:
       - echo "D"
    configuration:
      inputSteps:
      - name: step_E
        status:
        - success
        - skipped
  - name: step_G
    type: Bash
    execution:
      onExecute:
       - echo "D"
    configuration:
      inputSteps:
      - name: step_F
        status:
        - success

