pipelines:
  - name: AffinityGroupTest
    steps:
      - name: start
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
      - name: step_a
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
          priority: 1
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
      - name: step_b
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
          priority: 2
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
      - name: step_b1
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
          priority: 3
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"
      - name: step_b2
        type: Bash
        configuration:
          inputSteps:
            - name: start
          affinityGroup: group_a
          priority: 4
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_join
        type: Bash
        configuration:
          inputSteps:
            - name: step_a
            - name: step_b
            - name: step_b1
            - name: step_b2            
        execution:
          onExecute:
              - printenv
              - echo "Executing step on ${steplet_id}"

      - name: step_c
        type: Bash
        configuration:
          inputSteps:
            - name: step_join
          affinityGroup: group_b
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

      - name: step_d
        type: Bash
        configuration:
          inputSteps:
            - name: step_join
          affinityGroup: group_b
        execution:
          onExecute:
            - printenv
            - echo "Executing step on ${steplet_id}"

              
              