resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh1

pipelines:
  - name: PipelinesExt
    steps:
      - name: step1
        type: Bash
        configuration:
          affinityGroup: test
        execution: 
          onExecute:
            - echo 'step1'

      - name: step2
        type: test/PrintEnvVar
        configuration:
          affinityGroup: test
          inputSteps:
           - name: step1
          envVarName: 'run_number'
      - name: step4
        type: Bash
        configuration:
          inputSteps:
           - name: step3
          nodePool: u20
          runtime: 
           type: host
        execution:
          onExecute:
           - echo 'its working'
      - name: step3
        type: UploadArtifact
        configuration:
          affinityGroup: test
          inputSteps:
           - name: step1
          sourcePath: ./pipelines.yml
          targetPath: jfrogpipelines/uploads
          integrations:
            - name: art_v
          inputResources:
            - name: self_repo
