resources:
  - name: self_repo_tests
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{gitBranch}}$
      gitProvider: nawaz_gh1

pipelines:
  - name: Check_Save_Tests
    steps:
      - name: checkSaveTests
        type: Bash
        configuration:
          environmentVariables:
            "SUITES": 1000
            "PASSED": 250
            "FAILURE": 250
            "ERROR": 250
            "SKIPPED": 250
          inputResources:
            - name: self_repo_tests
        execution: 
          onExecute:
            - pushd $res_self_repo_tests_resourcePath
            - npm install
            - node generateTests.js
            - save_tests reports
