resources:
  - name: self_repo1
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^master$
      gitProvider: nawaz_gh

  - name: matrix_property_bag_in
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: property_bag
    type: PropertyBag
    configuration:
      key1: value1
      
  - name: output_1
    type: PropertyBag
    configuration:
      key1: value1
      
  - name: output_2
    type: PropertyBag
    configuration:
      key1: value1
  # - name: incoming
  #   type: IncomingWebhook
  #   configuration:
  #     webhookName: incoming

pipelines:
  - name: Pipeline_2
    steps:
     - name: step1
       type: Bash
       configuration:
         inputResources:
           - name: property_bag
       execution:
        onExecute:
          - echo "hello world"
          - update_run_description "a long text of description"
  - name: Pipeline
    preRun:
    configuration:
      inputResources:
        - name: property_bag
      outputResources:
        - name: output_1
      integrations:
        - name: nawaz_gh
    execution:
      onExecute:
        - echo 'Im running pre step'
    postRun:
      configuration:
        inputResources:
          - name: propertyo_bag
        outputResources:
          - name: output_2
        integrations:
          - name: nawaz_gh
      execution:
        onExecute:
          - echo 'Im running post step'
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: self_repo1
        execution: 
          onExecute:
            - echo "Step 1"
            - echo "Step1" >> file1
            - add_run_files ./file1 file
            - add_run_variables "step1_var=1"
            - update_run_description "a long longgggggggg ggg g g g g g g g g text of description"

      - name: step2
        type: Bash
        configuration:
          outputResources:
            - name: property_bag
          inputSteps:
            - name: step1
        execution: 
          onStart:
            - restore_run_files file ./file
            - echo "$step1_var"
          onExecute:
            - echo "Step 2"
            - cat file
            - echo "Step 2" >> file
            - add_run_files ./file file
            - date=$(date)
            - write_output property_bag "date=$date"
            - add_run_variables "step2_var=2"
            - update_run_description "Current date is ${date}"

      - name: step4
        type: Bash
        configuration:
          outputResources:
            - name: property_bag
          inputSteps:
            - name: step1
        execution: 
          onStart:
            - restore_run_files file ./file
            - echo "$step1_var"
          onExecute:
            - echo "Step 4"
            - cat file
            - echo "Step 4" >> file
            - add_run_files ./file file
            - date=$(date)
            - add_run_variables "step4_var=4"
            - write_output property_bag "date1=$date"

      - name: step3
        type: Bash
        configuration:
          inputResources:
            - name: property_bag
        execution: 
          onStart:
            - restore_run_files file ./file
            - echo "$step1_var"
            - echo "$step2_var"
            - echo "$step4_var"
          onExecute:
            - cat file
            - echo "Step 3" >> file
            - add_run_files ./file file
            - add_run_variables "step3_var=3"

      - name: step5
        type: Bash
        configuration:
          inputSteps:
            - name: step3
        execution: 
          onStart:
            - restore_run_files file ./file
            - echo "$step1_var"
            - echo "$step2_var"
            - echo "$step3_var"
            - echo "$step4_var"
          onExecute:
            - cat file
            - echo "Step 3" >> file
            - add_run_files ./file file
            - add_run_variables "step3_var=3"
