resources:
  - name: self_repo_tests
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^{{gitBranch}}$
      gitProvider: nawaz_gh

pipelines:
  - name: Check_Save_Tests
    steps:
      - name: checkSaveTests
        type: Bash
        configuration:
          inputResources:
            - name: self_repo_tests
        execution: 
          onExecute:
            - pushd $res_self_repo_tests_resourcePath
            - npm install